# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Version of andyboeh's Mediola2mqtt for Internorm blinds
version: "1.1.0"
slug: mediola2mqtt
description: Version of andyboeh's Mediola2mqtt for Internorm blinds
url: "https://github.com/mirandapoth/mediola2mqtt-repo/mediola2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello Mediola user ..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
